#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./$name"

  if [ "$platform" = "darwin" ]; then
    if [ "$arch" = "arm64" ]; then
      arch="amd64"
    fi
  else
    if [ "$arch" = "arm64" ]; then
      log::error "[$(timestamp)] linux arm64 is not supported"
      return 1
    fi
  fi

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/ContainerSSH/ContainerSSH/releases
  # example:
  #   https://github.com/ContainerSSH/ContainerSSH/releases/download/v2.1.7/containerssh-2.1.7-darwin-arm64.tar.gz
  #   https://github.com/ContainerSSH/ContainerSSH/releases/download/v2.1.7/containerssh-2.1.7-darwin-amd64.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${name}_${PACKAGE_CORE_VERSION#v}_${platform}_${arch}.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # make executable
  log::info "[$(timestamp)][package][$name] making executable ..."
  chmod 755 $bin_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  sudo mv $bin_file $usr_bin_dir

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
